# Generated by Django 3.1.5 on 2021-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210120_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
